#!/bin/bash

# cleanup
rm -v org-afraid-poison-db2php-*.nbm db2php-*.tar.bz2 *~ .*~

# parse version
. .version || exit 1

# create source tarball
./tarsrc || exit 1

# create netbeans module
ant clean || exit 1
ant nbm || exit 1
cp build/org-afraid-poison-db2php.nbm org-afraid-poison-db2php-${VERSION}.nbm || exit 1

# upload
. .passwd || exit 1
upcmd="../googlecode_upload.py -p $GPROJECT -u $GUSER -w $GPASSWORD"
$upcmd -s "Source code v${VERSION}" -l "OpSys-All,Type-Source,Featured" "db2php-${VERSION}.tar.bz2" || exit 1
$upcmd -s "NetBeans plugin v${VERSION}" -l "OpSys-All,Type-Package,NetBeans,Featured" "org-afraid-poison-db2php-${VERSION}.nbm" || exit 1

# NetBeans plugin page? curl maybe?


# SPAM!
curl --basic --user "${TUSER}:${TPASSWORD}" --data status="v${VERSION} of #db2php #netbeans #php plugin released \(^_^)/ http://code.google.com/p/db2php/" http://twitter.com/statuses/update.xml
